name: "Build Status"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  commitlint:
    name: "Commit lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

  check:
    name: "Code checks for [OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}]"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: "1.15"
            otp: "26.0"
          - elixir: "1.15.6"
            otp: "26.1.1"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Elixir/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Fetch the dependencies
        run: mix deps.get
      - name: Check (mix check)
        run: mix check
